if [ -d "${HOME}/antigen" ]
then
    source ${HOME}/antigen/antigen.zsh
    antigen-use oh-my-zsh
    antigen bundles <<EOBUNDLES
    git
    perl
    rvm
    cpanm
    zsh-users/zsh-syntax-highlighting
    command-not-found
    debian
    battery
    history-substring-search
    docker
    web-search
EOBUNDLES
fi

antigen-theme eastwood
antigen-apply

if [ -d "${HOME}/bin" ] ; then
    PATH="$HOME/bin:${PATH}"
fi


## -- rbenv setup
if [ -d "${HOME}/.rbenv/bin" ]
then
    export PATH="${HOME}/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi

#plenv
if [ -d "$HOME/.plenv/bin" ] 
then 
    export PATH="${HOME}/.plenv/bin:$PATH"
    eval "$(plenv init -)"
fi

export DISABLE_AUTO_TITLE=true

export GOPATH=${HOME}/Projects/golang
export PATH=${PATH}:${GOPATH}/bin
